settings:
  username: "danparizher"
  commit_message: "docs: update recent github activity"
  max_lines: 10
  readme_file: "./README.md"
  disabled_events:
    - "star"
    - "release"
    - "issue"
    - "commit"
  strings:
    PR_MERGED: 'Merged PR <a href="{pr_url}">{pr_link}</a> in <a href="{repo_url}">{repo_link}</a>'
    PR_OPENED: 'Opened PR <a href="{pr_url}">{pr_link}</a> in <a href="{repo_url}">{repo_link}</a>'
    ISSUE_OPENED: 'Opened issue <a href="{issue_url}">{issue_link}</a> in <a href="{repo_url}">{repo_link}</a>'
    ISSUE_CLOSED: 'Closed issue <a href="{issue_url}">{issue_link}</a> in <a href="{repo_url}">{repo_link}</a>'
    ISSUE_COMMENT: 'Commented on issue <a href="{issue_url}">{issue_link}</a> in <a href="{repo_url}">{repo_link}</a>'
    RELEASE: 'Released <a href="{release_url}">{release_link}</a> in <a href="{repo_url}">{repo_link}</a>'
